# Generated by Django 6.0.5 on 2026-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestation_type', models.CharField(choices=[('MARIAGE', 'Mariage / Fiançailles'), ('CIRCONCISION', 'Circoncision'), ('CLIP_MUSICAL', 'Clip Musical'), ('EDITORIAL', 'Session Éditoriale / Mode'), ('CORPORATE', 'Corporate / Événementiel')], max_length=30, verbose_name='Type de Prestation')),
                ('date_event', models.DateField(verbose_name="Date de l'événement")),
                ('lieu', models.CharField(max_length=150, verbose_name='Lieu (Ville, Salle...)')),
                ('prenom_epoux', models.CharField(blank=True, max_length=100, null=True, verbose_name="Prénom de l'Époux")),
                ('prenom_epouse', models.CharField(blank=True, max_length=100, null=True, verbose_name="Prénom de l'Épouse")),
                ('nom_client', models.CharField(blank=True, help_text="À remplir si ce n'est pas un mariage", max_length=150, null=True, verbose_name="Nom complet / Nom d'artiste")),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de Téléphone')),
                ('message', models.TextField(verbose_name='Racontez-nous votre projet')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
            ],
            options={
                'verbose_name': 'Réservations',
                'ordering': ['-date_event'],
            },
        ),
    ]
