# Generated by Django 6.0.5 on 2026-05-25 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nom_client',
        ),
        migrations.AddField(
            model_name='reservation',
            name='nom_contact',
            field=models.CharField(default='Non renseigné', max_length=100, verbose_name='Nom du Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='prenom_contact',
            field=models.CharField(default='non renseigné', max_length=100, verbose_name='Prénom du Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='recu_paiement',
            field=models.ImageField(blank=True, null=True, upload_to='recus_acomptes/', verbose_name='Reçu de virement (Acompte)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lieu',
            field=models.CharField(max_length=150, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(verbose_name='Détails du projet'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', "En attente d'acompte"), ('VERIFICATION', 'Reçu en cours de vérification'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
    ]
