# Generated by Django 6.0.5 on 2026-05-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='recu_paiement',
            field=models.ImageField(blank=True, null=True, upload_to='recus_acompte/', verbose_name='Reçu de paiement'),
        ),
    ]
