# Generated by Django 6.0.5 on 2026-05-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reservation_recu_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dynastie Film', max_length=200, verbose_name='Titre Principal')),
                ('subtitle', models.CharField(default='Espace Privé & Création', max_length=200, verbose_name='Sous-titre')),
                ('description', models.TextField(default='Production cinématographique et artistique haut de gamme.', verbose_name='Texte de Présentation')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Image de fond principale')),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Image section à propos')),
            ],
            options={
                'verbose_name': "Configuration Page d'Accueil",
                'verbose_name_plural': "Configuration Page d'Accueil",
            },
        ),
    ]
