# Generated by Django 6.0.5 on 2026-05-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesettings',
            options={'verbose_name': '1. Textes & Photos Fixes', 'verbose_name_plural': '1. Textes & Photos Fixes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': '2. Projet Portfolio (Scroll Horizontal)', 'verbose_name_plural': '2. Projets Portfolio (Scroll Horizontal)'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='non renseigné', upload_to='portfolio/', verbose_name='Image du projet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='description',
            field=models.TextField(default='Basé à Tizi Ouzou...', verbose_name='Texte de Présentation'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Image Grille 1'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Image Section Éditoriale'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='subtitle',
            field=models.CharField(default='Film', max_length=200, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='title',
            field=models.CharField(default='DYNASTIE', max_length=200, verbose_name='Titre Principal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Courte description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'apparition"),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre du projet'),
        ),
    ]
