# Generated by Django 6.0.5 on 2026-05-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_homesettings_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(choices=[(1, 'Case 1'), (2, 'Case 2'), (3, 'Case 3'), (4, 'Case 4'), (5, 'Case 5'), (6, 'Case 6')], unique=True, verbose_name='Numéro de la case (1 à 6)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='grid/', verbose_name='Image de fond')),
                ('text_content', models.CharField(default='1', max_length=50, verbose_name='Texte/Chiffre affiché')),
            ],
            options={
                'verbose_name': '2. Case de la Grille',
                'verbose_name_plural': '2. Cases de la Grille',
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DYNASTIE', max_length=100, verbose_name='Grand Titre Haut')),
                ('subtitle', models.CharField(default='Film', max_length=100, verbose_name='Grand Titre Bas')),
            ],
            options={
                'verbose_name': '1. Section Hero (Titres)',
                'verbose_name_plural': '1. Section Hero (Titres)',
            },
        ),
        migrations.CreateModel(
            name='HorizontalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description courte')),
                ('image', models.ImageField(upload_to='horizontal_portfolio/', verbose_name='Image du projet (600x450)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': '4. Projet Scroll Horizontal',
                'verbose_name_plural': '4. Projets Scroll Horizontal',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_italic_1', models.CharField(default='Film', max_length=50, verbose_name='Badge 1 (Italique)')),
                ('badge_normal_1', models.CharField(default='maker', max_length=50, verbose_name='Badge 1 (Normal)')),
                ('badge_italic_2', models.CharField(default='Photo', max_length=50, verbose_name='Badge 2 (Italique)')),
                ('badge_normal_2', models.CharField(default='grapher', max_length=50, verbose_name='Badge 2 (Normal)')),
                ('description', models.TextField(verbose_name='Texte de Présentation Principal')),
                ('editorial_image', models.ImageField(upload_to='editorial/', verbose_name='Image Éditoriale vertical')),
                ('editorial_subtitle', models.CharField(default="L'art du mouvement", max_length=100, verbose_name='Sous-titre Éditorial')),
                ('editorial_title', models.CharField(default='Capturer le temps...', max_length=200, verbose_name='Titre Éditorial')),
                ('editorial_text', models.TextField(verbose_name='Texte Éditorial')),
            ],
            options={
                'verbose_name': '3. Section Profession & Éditorial',
                'verbose_name_plural': '3. Section Profession & Éditorial',
            },
        ),
        migrations.DeleteModel(
            name='HomeSettings',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
