# Generated by Django 6.0.5 on 2026-05-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gridcard_herosection_horizontalproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='recu_paiement',
            field=models.ImageField(blank=True, null=True, upload_to='recus_acomptes/', verbose_name='Reçu de virement (Acompte)'),
        ),
    ]
