# Generated by Django 6.0.5 on 2026-05-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_reservation_recu_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hors_wilaya',
            field=models.BooleanField(default=False, verbose_name='Hors Wilaya de Tizi Ouzou (+3 000 DA)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='jours_supplementaires',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de journées supplémentaires'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mariage_horaire',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard (08h00 - 18h00)'), ('SOIREE', 'Soirée (20h00 - Fin)')], max_length=20, null=True, verbose_name='Horaire Mariage (Si applicable)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='option_drone',
            field=models.BooleanField(default=False, verbose_name='Option Drone (+20 000 DA)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lieu',
            field=models.CharField(max_length=150, verbose_name='Lieu (Commune, Adresse)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(verbose_name='Détails / Exigences du client'),
        ),
    ]
