# Generated by Django 6.0.5 on 2026-05-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reservation_hors_wilaya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dates_supplementaires',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
