# Generated by Django 6.0.5 on 2026-05-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reservation_dates_supplementaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='mariage_horaire',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard (08h00 - 18h00)'), ('TOUTE LA JOURNÉE', 'Toute la journée (08h00 - FIN)'), ('SOIREE', 'Soirée (20h00 - Fin)')], max_length=20, null=True, verbose_name='Horaire Mariage (Si applicable)'),
        ),
    ]
