# Generated by Django 6.0.5 on 2026-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_reservation_mariage_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Détails / Exigences du client'),
        ),
    ]
