# Generated by Django 6.0.5 on 2026-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_reservation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('categorie', models.CharField(choices=[('mariage', 'Mariage'), ('fiancaille', 'Fiançailles'), ('shooting', 'Shooting')], max_length=50)),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Photo')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
