# Generated by Django 6.0.5 on 2026-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='projet',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/videos/', verbose_name='Fichier Vidéo'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(upload_to='portfolio/', verbose_name='Photo ou Miniature Vidéo'),
        ),
    ]
