# Generated by Django 6.0.5 on 2026-05-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_projet_media_type_projet_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='video_file',
        ),
        migrations.AddField(
            model_name='projet',
            name='fichier',
            field=models.FileField(default='non renseigné', upload_to='portfolio/', verbose_name='Image ou Vidéo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projet',
            name='categorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projet',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
