# Generated by Django 6.0.5 on 2026-05-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_projet_image_remove_projet_media_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='hero_videos/')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (1, 2, 3...)")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
