# Generated by Django 6.0.5 on 2026-05-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='Manifeste', max_length=50, unique=True)),
                ('title', models.CharField(default='Notre Vision', max_length=200)),
                ('description', models.TextField(default='Votre texte par défaut ici...')),
            ],
        ),
    ]
