# Generated by Django 6.0.5 on 2026-05-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('video', 'Vidéaste / Montage'), ('photo', 'Photographie'), ('conseil', 'Conseils Techniques')], max_length=50)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(upload_to='education/')),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
