# Generated by Django 6.0.5 on 2026-05-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_educationarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilMariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('prep', 'Préparatifs'), ('timing', 'Organisation & Timing'), ('video', 'Conseils Vidéo')], max_length=50)),
                ('resume', models.CharField(max_length=300)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(upload_to='conseils/')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
