# Generated by Django 6.0.5 on 2026-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_conseilmariage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conseilmariage',
            options={'ordering': ['ordre', '-date_pub']},
        ),
        migrations.AddField(
            model_name='conseilmariage',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conseilmariage',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (1, 2, 3...)"),
        ),
        migrations.AlterField(
            model_name='conseilmariage',
            name='contenu',
            field=models.TextField(help_text='Texte complet du conseil'),
        ),
        migrations.AlterField(
            model_name='conseilmariage',
            name='resume',
            field=models.CharField(help_text="Phrase d'accroche visible avant clic", max_length=300),
        ),
    ]
